import { Widget, Product } from "./definitions";

const widgets: Widget[] = [
    {
        id: 1,
        caption: "- O MELHOR LUGAR PARA JOGAR",
        title: "Consoles Xbox",
        price: 3892,
        description:
            "Economize até 50% em jogos selecionados para Xbox. Ganhe 3 meses de PC Game Pass por US$ 2.",
        imagePath: "/xbox.png",
        imagePosition: "right",
        href: "#",
        size: "lg",
        backgroundColor: "light",
    },
    {
        id: 2,
        caption: "- VENDAS DE VERÃO",
        title: "Novo Google Pixel 6 Pro",
        imagePath: "/google-pixel-6-pro.png",
        imagePosition: "right",
        discount: "20% OFF",
        href: "#",
        size: "md",
        backgroundColor: "dark",
    },
    {
        id: 3,
        title: "Xiaomi FlipBuds Pro",
        imagePath: "/xiaomi-flip-buds-pro.png",
        imagePosition: "left",
        href: "#",
        size: "md",
        backgroundColor: "light",
    },
];

const bestDeals: Product[] = [
    {
        id: 1,
        title: "PlayStation®5 Slim Edição Digital com 2 Jogos ",
        description:
            "Experimente o carregamento extremamente rápido de um SSD de ultravelocidade, imersão mais profunda com ajuda da resposta tátil, gatilhos adaptáveis e áudio 3D, além dos dois jogos PlayStation® incríveis.",
        thumbnail: "/best-deals-1.png",
        price: 2707.9,
        discount: 20,
        availableQuantity: 10,
        score: 52.677,
        isAvailable: true,
        isActive: true,
        isHot: true,
    },
    {
        id: 2,
        title: "Fones de ouvido esportivos Bose - Fones de ouvido sem fio",
        description: null,
        thumbnail: "/best-deals-2.png",
        price: 367.9,
        discount: null,
        availableQuantity: 0,
        score: null,
        isAvailable: false,
        isActive: true,
        isHot: false,
    },
    {
        id: 3,
        title: "Simple Mobile 4G LTE Prepaid Smartphone",
        description: null,
        thumbnail: "/best-deals-3.png",
        price: 1899.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 4,
        title: "4K UHD LED Smart TV with Chromecast Built-in",
        description: null,
        thumbnail: "/best-deals-4.png",
        price: 3987.9,
        discount: 19,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 5,
        title: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
        description: null,
        thumbnail: "/best-deals-5.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 6,
        title: "Máquina de lavar portátil, capacidade de 11 libras, modelo 18NMFIAM",
        description: null,
        thumbnail: "/best-deals-6.png",
        price: 587.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 7,
        title: "Portable Wshing Machine, 11lbs capacity Model 18NMFIAM",
        description: null,
        thumbnail: "/best-deals-7.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 8,
        title: "2-Barrel Carburetor Carb 2100 Engine Increase Horsepower",
        description: null,
        thumbnail: "/best-deals-8.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: true,
    },
    {
        id: 9,
        title: "JBL FLIP 4 - Waterproof Portable Bluetooth Speaker - Black",
        description: null,
        thumbnail: "/best-deals-9.png",
        price: 534.9,
        discount: 32,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
];

export { widgets, bestDeals };
