import { Product, Category } from "./definitions";

const bestDeals: Product[] = [
    {
        id: 1,
        title: "PlayStation®5 Slim Edição Digital com 2 Jogos ",
        description:
            "Experimente o carregamento extremamente rápido de um SSD de ultravelocidade, imersão mais profunda com ajuda da resposta tátil, gatilhos adaptáveis e áudio 3D, além dos dois jogos PlayStation® incríveis.",
        thumbnail: "/best-deals/best-deals-1.png",
        price: 2707.9,
        discount: 20,
        availableQuantity: 10,
        score: 52.677,
        isAvailable: true,
        isActive: true,
        isHot: true,
    },
    {
        id: 2,
        title: "Fones de ouvido esportivos Bose - Fones de ouvido sem fio",
        description: null,
        thumbnail: "/best-deals/best-deals-2.png",
        price: 367.9,
        discount: null,
        availableQuantity: 0,
        score: 22.677,
        isAvailable: false,
        isActive: true,
        isHot: false,
    },
    {
        id: 3,
        title: "Simple Mobile 4G LTE Prepaid Smartphone",
        description: null,
        thumbnail: "/best-deals/best-deals-3.png",
        price: 1899.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 4,
        title: "4K UHD LED Smart TV with Chromecast Built-in",
        description: null,
        thumbnail: "/best-deals/best-deals-4.png",
        price: 3987.9,
        discount: 19,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 5,
        title: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
        description: null,
        thumbnail: "/best-deals/best-deals-5.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 6,
        title: "Máquina de lavar portátil, capacidade de 11 libras, modelo 18NMFIAM",
        description: null,
        thumbnail: "/best-deals/best-deals-6.png",
        price: 587.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 7,
        title: "Portable Wshing Machine, 11lbs capacity Model 18NMFIAM",
        description: null,
        thumbnail: "/best-deals/best-deals-7.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 8,
        title: "2-Barrel Carburetor Carb 2100 Engine Increase Horsepower",
        description: null,
        thumbnail: "/best-deals/best-deals-8.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: true,
    },
    {
        id: 9,
        title: "JBL FLIP 4 - Waterproof Portable Bluetooth Speaker - Black",
        description: null,
        thumbnail: "/best-deals/best-deals-9.png",
        price: 534.9,
        discount: 32,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
];

const categories: Category[] = [
    {
        id: 1,
        title: "Computadores e Laptops",
        imagePath: "/categories/computadores-e-laptops.png",
        href: "#",
    },
    {
        id: 2,
        title: "Acessórios de Computador",
        imagePath: "/categories/acessorios-de-computador.png",
        href: "#",
    },
    {
        id: 3,
        title: "SmartPhone",
        imagePath: "/categories/smartphone.png",
        href: "#",
    },
    {
        id: 4,
        title: "Headphone",
        imagePath: "/categories/headphones.png",
        href: "#",
    },
    {
        id: 5,
        title: "Acessórios Mobile",
        imagePath: "/categories/acessorios-mobile.png",
        href: "#",
    },
    {
        id: 6,
        title: "Consoles e Jogos",
        imagePath: "/categories/consoles-e-jogos.png",
        href: "#",
    },
    {
        id: 7,
        title: "Câmeras e Fotos",
        imagePath: "/categories/cameras-e-fotos.png",
        href: "#",
    },
    {
        id: 8,
        title: "TV e Eletrodomésticos",
        imagePath: "/categories/tv-e-eletrodomesticos.png",
        href: "#",
    },
    {
        id: 9,
        title: "GPS e Navegação",
        imagePath: "/categories/gps-e-navegacao.png",
        href: "#",
    },
    {
        id: 10,
        title: "Roupas e Acessórios",
        imagePath: "/categories/roupas-e-acessorios.png",
        href: "#",
    },
]

const featuredProducts: Product[] = [
    {
        id: 1,
        title: "PlayStation®5 Slim Edição Digital com 2 Jogos ",
        description:
            "Experimente o carregamento extremamente rápido de um SSD de ultravelocidade, imersão mais profunda com ajuda da resposta tátil, gatilhos adaptáveis e áudio 3D, além dos dois jogos PlayStation® incríveis.",
        thumbnail: "/best-deals/best-deals-1.png",
        price: 2707.9,
        discount: 20,
        availableQuantity: 10,
        score: 52.677,
        isAvailable: true,
        isActive: true,
        isHot: true,
    },
    {
        id: 2,
        title: "Fones de ouvido esportivos Bose - Fones de ouvido sem fio",
        description: null,
        thumbnail: "/best-deals/best-deals-2.png",
        price: 367.9,
        discount: null,
        availableQuantity: 0,
        score: null,
        isAvailable: false,
        isActive: true,
        isHot: false,
    },
    {
        id: 3,
        title: "Simple Mobile 4G LTE Prepaid Smartphone",
        description: null,
        thumbnail: "/best-deals/best-deals-3.png",
        price: 1899.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 4,
        title: "4K UHD LED Smart TV with Chromecast Built-in",
        description: null,
        thumbnail: "/best-deals/best-deals-4.png",
        price: 3987.9,
        discount: 19,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 5,
        title: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
        description: null,
        thumbnail: "/best-deals/best-deals-5.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 6,
        title: "Máquina de lavar portátil, capacidade de 11 libras, modelo 18NMFIAM",
        description: null,
        thumbnail: "/best-deals/best-deals-6.png",
        price: 587.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 7,
        title: "Portable Wshing Machine, 11lbs capacity Model 18NMFIAM",
        description: null,
        thumbnail: "/best-deals/best-deals-7.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: false,
    },
    {
        id: 8,
        title: "2-Barrel Carburetor Carb 2100 Engine Increase Horsepower",
        description: null,
        thumbnail: "/best-deals/best-deals-8.png",
        price: 1987.9,
        discount: null,
        availableQuantity: 10,
        score: null,
        isAvailable: true,
        isActive: true,
        isHot: true,
    },
];

const categoryProducts = [
    {
        id: 1,
        title: "Computadores e Laptops",
        products: [
            {
                id: 1,
                title: "PlayStation®5 Slim Edição Digital com 2 Jogos ",
                description:
                    "Experimente o carregamento extremamente rápido de um SSD de ultravelocidade, imersão mais profunda com ajuda da resposta tátil, gatilhos adaptáveis e áudio 3D, além dos dois jogos PlayStation® incríveis.",
                thumbnail: "/best-deals/best-deals-1.png",
                price: 2707.9,
                discount: 20,
                availableQuantity: 10,
                score: 52.677,
                isAvailable: true,
                isActive: true,
                isHot: true,
            },
            {
                id: 2,
                title: "Fones de ouvido esportivos Bose - Fones de ouvido sem fio",
                description: null,
                thumbnail: "/best-deals/best-deals-2.png",
                price: 367.9,
                discount: null,
                availableQuantity: 0,
                score: null,
                isAvailable: false,
                isActive: true,
                isHot: false,
            },
            {
                id: 3,
                title: "Simple Mobile 4G LTE Prepaid Smartphone",
                description: null,
                thumbnail: "/best-deals/best-deals-3.png",
                price: 1899.9,
                discount: null,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ]
    },
    {
        id: 2,
        title: "SmartPhones",
        products: [
            {
                id: 4,
                title: "4K UHD LED Smart TV with Chromecast Built-in",
                description: null,
                thumbnail: "/best-deals/best-deals-4.png",
                price: 3987.9,
                discount: 19,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 5,
                title: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
                description: null,
                thumbnail: "/best-deals/best-deals-5.png",
                price: 1987.9,
                discount: null,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 6,
                title: "Máquina de lavar portátil, capacidade de 11 libras, modelo 18NMFIAM",
                description: null,
                thumbnail: "/best-deals/best-deals-6.png",
                price: 587.9,
                discount: null,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ]
    },
    {
        id: 3,
        title: "TV e Eletrodomésticos",
        products: [
            {
                id: 7,
                title: "Portable Wshing Machine, 11lbs capacity Model 18NMFIAM",
                description: null,
                thumbnail: "/best-deals/best-deals-7.png",
                price: 1987.9,
                discount: null,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 8,
                title: "2-Barrel Carburetor Carb 2100 Engine Increase Horsepower",
                description: null,
                thumbnail: "/best-deals/best-deals-8.png",
                price: 1987.9,
                discount: null,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: true,
            },
            {
                id: 9,
                title: "JBL FLIP 4 - Waterproof Portable Bluetooth Speaker - Black",
                description: null,
                thumbnail: "/best-deals/best-deals-9.png",
                price: 534.9,
                discount: 32,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ]
    },
    {
        id: 4,
        title: "Consoles e Jogos",
        products: [
            {
                id: 10,
                title: "4K UHD LED Smart TV with Chromecast Built-in",
                description: null,
                thumbnail: "/best-deals/best-deals-4.png",
                price: 3987.9,
                discount: 19,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 11,
                title: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
                description: null,
                thumbnail: "/best-deals/best-deals-5.png",
                price: 1987.9,
                discount: null,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 12,
                title: "Máquina de lavar portátil, capacidade de 11 libras, modelo 18NMFIAM",
                description: null,
                thumbnail: "/best-deals/best-deals-6.png",
                price: 587.9,
                discount: null,
                availableQuantity: 10,
                score: null,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ]
    },
]

const priceMarks = [
    { id: 1, title: "Todos os preços" },
    { id: 2, title: "Menor que R$ 100" },
    { id: 3, title: "R$ 100 - R$ 500" },
    { id: 4, title: "R$ 500 - R$ 1.000" },
    { id: 5, title: "R$ 1.000 - R$ 3.000" },
    { id: 6, title: "R$ 3.000 - R$ 6.000" },
    { id: 7, title: "Acima de R$ 6.000" },
];  

const popularBrands = [
    { id: 1, title: "Apple" },
    { id: 2, title: "Microsoft" },
    { id: 3, title: "Dell" },
    { id: 4, title: "Symphony" },
    { id: 5, title: "Sony" },
    { id: 6, title: "LG" },
    { id: 7, title: "One Plus" },
    { id: 8, title: "Google" },
    { id: 9, title: "Samsung" },
    { id: 10, title: "HP" },
    { id: 11, title: "Xiaomi" },
    { id: 12, title: "Panasonic" }
];

const popularTags = [
    {
        id: 1,
        title: "Games",
    },
    {
        id: 2,
        title: "iphone",
    },
    {
        id: 3,
        title: "TV",
    },
    {
        id: 4,
        title: "Laptops",
    },
    {
        id: 5,
        title: "Macbook",
    },
    {
        id: 6,
        title: "SSD",
    },
    {
        id: 7,
        title: "Graphic Card",
    },
    {
        id: 8,
        title: "Power bank",
    },
    {
        id: 9,
        title: "Smart TV",
    },
    {
        id: 10,
        title: "Speaker",
    },
    {
        id: 11,
        title: "Tablet",
    },
    {
        id: 12,
        title: "Microwave",
    },
    {
        id: 13,
        title: "Samsung",
    },
];

export { 
    bestDeals, 
    categories, 
    featuredProducts, 
    categoryProducts,
    priceMarks,
    popularBrands,
    popularTags
};
