import { CategoryProducts } from "@/lib/definitions";

export const categoryProducts: CategoryProducts[] = [
    {
        id: 1,
        title: "Computadores e Laptops",
        products: [
            {
                id: 1,
                title: "PlayStation®5 Slim Edição Digital com 2 Jogos ",
                description:
                    "Experimente o carregamento extremamente rápido de um SSD de ultravelocidade, imersão mais profunda com ajuda da resposta tátil, gatilhos adaptáveis e áudio 3D, além dos dois jogos PlayStation® incríveis.",
                thumbnail: "/products/product-1/photo-1.png",
                price: 2707.9,
                discount: 20,
                availableQuantity: 10,
                score: 52.677,
                isAvailable: true,
                isActive: true,
                isHot: true,
            },
            {
                id: 2,
                title: "Fones de ouvido esportivos Bose - Fones de ouvido sem fio",
                thumbnail: "/products/product-2/photo-1.png",
                price: 367.9,
                availableQuantity: 0,
                isAvailable: false,
                isActive: true,
                isHot: false,
            },
            {
                id: 3,
                title: "Simple Mobile 4G LTE Prepaid Smartphone",
                thumbnail: "/products/product-3/photo-1.png",
                price: 1899.9,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ],
    },
    {
        id: 2,
        title: "SmartPhones",
        products: [
            {
                id: 4,
                title: "4K UHD LED Smart TV with Chromecast Built-in",
                thumbnail: "/products/product-4/photo-1.png",
                price: 3987.9,
                discount: 19,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 5,
                title: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
                thumbnail: "/products/product-5/photo-1.png",
                price: 1987.9,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 6,
                title: "Máquina de lavar portátil, capacidade de 11 libras, modelo 18NMFIAM",
                thumbnail: "/products/product-6/photo-1.png",
                price: 587.9,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ],
    },
    {
        id: 3,
        title: "TV e Eletrodomésticos",
        products: [
            {
                id: 7,
                title: "Portable Wshing Machine, 11lbs capacity Model 18NMFIAM",
                thumbnail: "/products/product-7/photo-1.png",
                price: 1987.9,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 8,
                title: "2-Barrel Carburetor Carb 2100 Engine Increase Horsepower",
                thumbnail: "/products/product-8/photo-1.png",
                price: 1987.9,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: true,
            },
            {
                id: 9,
                title: "JBL FLIP 4 - Waterproof Portable Bluetooth Speaker - Black",
                thumbnail: "/products/product-9/photo-1.png",
                price: 534.9,
                discount: 32,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ],
    },
    {
        id: 4,
        title: "Consoles e Jogos",
        products: [
            {
                id: 10,
                title: "4K UHD LED Smart TV with Chromecast Built-in",
                thumbnail: "/products/product-4/photo-1.png",
                price: 3987.9,
                discount: 19,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 11,
                title: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
                thumbnail: "/products/product-5/photo-1.png",
                price: 1987.9,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
            {
                id: 12,
                title: "Máquina de lavar portátil, capacidade de 11 libras, modelo 18NMFIAM",
                thumbnail: "/products/product-6/photo-1.png",
                price: 587.9,
                availableQuantity: 10,
                isAvailable: true,
                isActive: true,
                isHot: false,
            },
        ],
    },
];
